# Non-essential additional services

version: '3'
services:
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

  portainer:
    restart: on-failure
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer_init:
    depends_on:
      - portainer
    image: alpine/curl
    restart: on-failure
    environment:
      - PORTAINER_PASSWORD=${PORTAINER_PASSWORD}
    volumes:
      - ./docker/portainer/setup.sh:/setup.sh
    command: ./setup.sh

  pgadmin:
    restart: on-failure
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
  minio_data:
