{
 "title": "AppFlowy Cloud",
 "description": "dashboard to monitor appflowy cloud server",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Average Response(ms) for endpoints",
   "type": "timeseries",
   "description": "(rate of total latency)/(rate of total request made) for every endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(appflowy_cloud__requests_latency_total[$__interval])/rate(appflowy_cloud__requests_count_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "non 200 http status code for every endpoint",
   "type": "timeseries",
   "description": "rate of http request with returned response of non 200",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(appflowy_cloud__requests_result_total{status_code!~\"2..\"}[$__interval])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of requests per second for each endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(appflowy_cloud__requests_count_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}