// This file is @generated by prost-build.
/// *
/// All messages send between client/server are wrapped into a `Message`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
  #[prost(oneof = "message::Payload", tags = "1, 2")]
  pub payload: ::core::option::Option<message::Payload>,
}
/// Nested message and enum types in `Message`.
pub mod message {
  #[derive(Clone, PartialEq, ::prost::Oneof)]
  pub enum Payload {
    #[prost(message, tag = "1")]
    CollabMessage(super::super::collab::CollabMessage),
    #[prost(message, tag = "2")]
    UserMessage(super::super::user::UserMessage),
  }
}
