// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkspaceNotification {
  #[prost(oneof = "workspace_notification::Payload", tags = "1, 2")]
  pub payload: ::core::option::Option<workspace_notification::Payload>,
}
/// Nested message and enum types in `WorkspaceNotification`.
pub mod workspace_notification {
  #[derive(Clone, PartialEq, ::prost::Oneof)]
  pub enum Payload {
    #[prost(message, tag = "1")]
    ProfileChange(super::UserProfileChange),
    #[prost(message, tag = "2")]
    PermissionChanged(super::PermissionChanged),
  }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserProfileChange {
  #[prost(int64, tag = "1")]
  pub uid: i64,
  #[prost(string, optional, tag = "2")]
  pub name: ::core::option::Option<::prost::alloc::string::String>,
  #[prost(string, optional, tag = "3")]
  pub email: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PermissionChanged {
  #[prost(string, tag = "1")]
  pub object_id: ::prost::alloc::string::String,
  #[prost(uint32, tag = "2")]
  pub reason: u32,
}
