// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UserMessage {
  #[prost(oneof = "user_message::Payload", tags = "1")]
  pub payload: ::core::option::Option<user_message::Payload>,
}
/// Nested message and enum types in `UserMessage`.
pub mod user_message {
  #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
  pub enum Payload {
    #[prost(message, tag = "1")]
    ProfileChange(super::UserProfileChange),
  }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UserProfileChange {
  #[prost(int64, tag = "1")]
  pub uid: i64,
}
