FROM appflowy_cloud-appflowy_cloud_runtime:latest
CMD ["ls"]
# COPY --from=builder /app/target/release/appflowy_cloud /usr/local/bin/appflowy_cloud
# COPY --from=builder /app/configuration configuration
# ENV APP_ENVIRONMENT production
# ENV RUST_BACKTRACE 1
# CMD ["appflowy_cloud"]
