application:
  port: 8000
  host: 0.0.0.0
  server_key: "Should-Use-The-Custom-Server-Key"
  tls_config: "no_tls"
  data_dir: "./data"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "postgres"
websocket:
  heartbeat_interval: 8
  client_timeout: 10
redis_uri: "redis://127.0.0.1:6379"
gotrue:
  base_url: "http://127.0.0.1:9999"
