application:
  port: 8000
  host: 0.0.0.0
  server_key: "Should-Use-The-Custom-Server-Key"
  tls_config: "no_tls"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "appflowy"
redis_uri: "redis://127.0.0.1:6379"
