application:
  host: 127.0.0.1
  base_url: "https://127.0.0.1"
database:
  require_ssl: false
  port: 5433
redis_uri: "redis://127.0.0.1:6380"
gotrue:
  base_url: "http://127.0.0.1:9998"
  jwt_secret: "hello456"
