name: Security audit
on:
  workflow_dispatch:
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run:
          cargo deny check advisories
