name: Build and Push latest docker image

on: [pull_request, push]
#on:
#  push:
#    branches:
#      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build appflowy-cloud
        run: |
          docker-compose build appflowy_cloud

      - name: Push appflowy-cloud
        run: |
          docker-compose push appflowy_cloud

      - name: Build appflowy-cloud admin frontend
        run: |
          docker-compose build admin_frontend

      - name: Push appflowy-cloud admin frontend
        run: |
          docker-compose push admin_frontend

      - name: Logout from Docker Hub
        if: always()
        run: docker logout
